config/routes.rb
Rails.application.routes.draw do

  get 'cart/show'
  root to: "session#new"

  get "/login" => "session#new" # ahow the login form
  post "/login" => "session#create" # submit the login and authenticate
  delete "/login" => "session#destroy"

  post "/products/:id/add_to_cart" => "cart#add", as: :add_to_cart

  get "/cart" => "cart#show", as:"show_cart"

  delete "/cart/:id/remove" => "cart#remove", as: :remove_from_cart

  get "/cart/:id/check_out" => "cart#check_out", as: :check_out

  get 'pages/home'
  get '/search' => "products#search", as: :product_search
  resources :users , :products, :categories
  # resources :products
  # resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord

  geocoded_by :address
  after_validation :geocode

  has_many :carts
  has_many :users, through: :carts
  belongs_to :category, optional: true

  validates :name, :price, :category_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password


  has_many :carts
  has_many :products, through: :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  def check_if_logged_in
    unless @current_user.present?
      flash[:error] = "You must be logged in to view that page."
      redirect_to login_path
    end
  end

  private

  def fetch_user

    if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]
    end
    # just in case we r dealing with a state user ID
    # (i.e. )
    session[:user_id] = nil unless @current_user.present?

  end
  def check_if_admin
    unless @current_user.admin
      flash[:error] = "You must be logged in as admin to view that page."
      redirect_to login_path
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @cart = Cart.where user_id: @current_user.id
  end
  def cart
  end
  def add
    Cart.create(
      user_id: @current_user.id,
      product_id: params[:id]
    )
    redirect_to show_cart_path
  end
  def remove
    # raise 'hell'
    Cart.destroy params[:id]
    redirect_to show_cart_path
  end

  def check_out

  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_if_logged_in, only: [:index, :show]

  def new
  end

  def create
  end

  def index
    @categories = Category.all
  end

  def show
    @products = Product.where category_id: params[:id]
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def delete

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :check_if_logged_in, only: [:index, :show, :new]
  before_action :check_if_admin, except: [:index, :show, :search]
  before_action :get_product, only:[:show, :edit, :update]


  def new
    @product = Product.new
  end

  def create
    product = Product.create product_params
    if product.persisted?
      if params[:file].present?
        req = Cloudinary::Uploader.upload(params[:file])
        product.image = req["public_id"]
        product.save
      end
      redirect_to category_path( product.category )
    else
      flash[:errors] = product.errors.full_messages
      redirect_to new_product_path
    end
  end

  def index
    @products = Product.find_by params[:id]
  end

  def show
  end

  def edit
  end

  def update
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @product.image = req["public_id"]
    end
    @product.update product_params
    redirect_to product_path
  end

  def destroy
    p = Product.find params[:id]
    p.destroy
    # raise 'hell'
    redirect_to category_path(p.category)
  end

  def search
    @products = Product.where("name ILIKE ?", "%#{params[:query]}%")
  end

  private
  def get_product
    @product = Product.find params[:id]
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :description, :address, :category_id, :image)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:email]

    if user.present? && user.authenticate( params[:password] )
      session[:user_id] = user.id
      redirect_to categories_path
    else
      flash[:error] = "Invalid emial address or password"
      redirect_to login_path
    end

  end

  def destroy
    session[:user_id] = nil # this clears the cookie
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_in, only: [:index]
  before_action :check_if_admin, only: [:index]
  def new
    @user = User.new
  end

  def create
    user = User.create user_params
    if user.persisted?
      session[:user_id] = user.id
      redirect_to categories_path
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart/show.html.erb
<h1>Show Cart</h1>
<table class="table table-striped table-success">
  <thead class="thead-dark">
    <tr scope="row">
      <th scope="col"><strong>Product</strong></th>
      <th scope="col"><strong>Category</strong></th>
      <th scope="col"><strong>Price</strong></th>
      <th scope="col"></th>
    </tr>
  </thead>
    <tbody>
    <% @cart.each do |c| %>
    <tr>
      <td>
        <%= cl_image_tag c.product.image, class: :product_cart_image%>
      </td>
      <td>
        <%= c.product.name %>
      </td>
      <td>
        <%= number_to_currency(c.product.price) %>
      </td>
      <td>
        <%= link_to "Delete", remove_from_cart_path(c.id), method: :delete %>
      </td>
    </tr>
    <% end %>
    </tbody>
</table>
<br>
<br>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% @categories.each do |c| %>
  <%= link_to category_path(c), class: :link_txt_dec do %>
    <div class="products_all">
      <%= image_tag c.image%>
      <%= c.name %>
    </div>
  <% end %>
<% end %>

app/views/categories/show.html.erb
<h1>Products</h1>
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag "https://foodheart.org/assets/toys-main-c5824ff6cd696a4d896490aa7fad8ba2.png", class:"d-block img-fluid"%>
    </div>
    <div class="carousel-item">
      <%= image_tag "designer_chocker.png", class:"d-block img-fluid"%>
    </div>
    <div class="carousel-item">
      <%= image_tag "teddys.jpeg", class:"d-block img-fluid"%>
    </div>
    <div class="carousel-item">
      <%= image_tag "two_pots.jpeg", class:"d-block img-fluid"%>
    </div>
  </div>
</div>
<% @products.each do |p| %>
    <%= link_to product_path(p), class: :link_txt_dec do %>
      <div class="products_all">
        <% if p.image.present? %>
          <%= cl_image_tag(p.image)%>
        <% else %>
          <%= image_tag "no_image.png" %>
        <% end %>
        <%= p.name %>
        <%= number_to_currency(p.price) %>
      </div>
    <% end %>
<% end %>

<div id="map"> </div>
<script>
  function initMap() {
    // var myLatLng = {lat: -33.87145, lng: 151.20443};
    var bounds = new google.maps.LatLngBounds();
    var map = new google.maps.Map(document.getElementById('map'));
    // getting products lat, lng, name from instance variable
    var products = <%= @products.map{ |p| {lat: p.latitude, lng: p.longitude, name: p.name } }.to_json.html_safe %>;
    // looping over products to make marker for each product
    for(let i=0; i < products.length; i++)
    {
      var marker = new google.maps.Marker({
        position: products[i],
        map: map,
        title: products[i].name
      });
      bounds.extend(marker.position);
    }
    map.fitBounds( bounds );
  }
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAJ0a73hhDIswEV4mTLGjmLIx4oHHFUelM&callback=initMap">
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <div class="main">
      <h1>Shopping Cart</h1>
      <nav class="right_nav">
        <% if @current_user.present?%>
          <%= form_tag product_search_path, method: :get do %>
            <%= text_field_tag :query, nil, placeholder: 'Serch Keywords' %>
            <%= submit_tag "Search" %>
          <% end %>
          <%= link_to 'Home', categories_path%>
          <%= link_to 'Cart', show_cart_path%>
          Welcome, <%= @current_user.name%>
          |
           <% if @current_user.admin? %>
             <%= link_to 'Add Product', new_product_path %>
             |
           <% end %>
          <%= link_to 'Logout', login_path, method: :delete%>
        <% else %>
          <%= link_to 'login', login_path%>
          |
          <%= link_to 'Sign Up', new_user_path%>
        <% end %>
      </nav>
      <div class="clearfix">
        <nav class="left_nav">

        </nav>
      </div>
      <hr>
      <%= yield %>
      <hr>
      <footer class="footer">
      &copy; Free Shop
    </footer>
  </div>
</body>
</html>

app/views/pages/cart.html.erb
<h1>Show Cart</h1>

<table>
    <tr>
      <td><strong>Product</strong></td>
      <td><strong>Category</strong></td>
      <td><strong>Price</strong></td>
      <td></td>
    </tr>
    <% @cart.each do |c| %>
    <tr>
      <td>
        <%= cl_image_tag c.product.image, class: :product_cart_image%>
      </td>
      <td>
        <%= c.product.name %>
      </td>
      <td>
        <%= number_to_currency(c.product.price) %>
      </td>
      <td>
        <%= link_to "Delete", remove_from_cart_path(c.id), method: :delete %>
      </td>
    </tr>
    <% end %>
</table>

app/views/pages/home.html.erb
<h1>This is the home page</h1>
<p>Home page</p>

app/views/products/_form.html.erb
<% if flash[:errors] %>
  <strong>Please correct the following errors:</strong>
  <ol>
    <% flash[:errors].each do |e| %>
      <li><%= e %></li>
    <% end %>
  </ol>
<% end %>
<%= form_for(@product, :html => {:multipart => true}) do |f| %>
  <%= f.label :name, 'Name :'%>
  <%= f.text_field :name, class: :field%>
  <br>
  <%= f.label :price, 'Price :'%>
  <%= f.text_field :price, class: :field%>
  <br>
  <%= f.label :description, 'Description :'%>
  <%= f.text_field :description, class: :field%>
  <br>
  <%= f.label :address, 'Address :'%>
  <%= f.text_field :address, class: :field%>
  <br>
  <%= f.label :category_id, 'Category :' %>
  <%= f.select :category_id, Category.pluck(:name, :id), include_blank: true , class: :field%>
  <br>
  <%= f.label :image, 'Image :'%>
  <%= f.cl_image_upload :image, class: :field%>
  <br>
  <%= f.submit%>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render partial: "form"%>

app/views/products/index.html.erb
<h1>All Products</h1>
<% @products.each do |p| %>
  <%= link_to product_path(p), class: :link_txt_dec do %>
    <div class="products_all">
      <%= image_tag p.image%>
      <%= p.name %>$<%= p.price%>
    </div>
  <% end %>
<% end %>

app/views/products/new.html.erb
<h1>Add new Product</h1>
<%= render partial: "form"%>

app/views/products/search.html.erb
<h1>Products</h1>
<% if @products.empty? %>
  <h4>No Results Found...</h4>
<% else %>
  <% @products.each do |p| %>
      <%= link_to product_path(p), class: :link_txt_dec do %>
        <div class="products_all">
          <% if p.image.present? %>
            <%= cl_image_tag(p.image)%>
          <% else %>
            <%= image_tag "no_image.png" %>
          <% end %>
          <%= p.name %>
          <%= number_to_currency(p.price) %>
        </div>
      <% end %>
  <% end %>
<% end %>

app/views/products/show.html.erb
<h1>Product <%= @product.name%></h1>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <% if @product.image.present? %>
        <%= cl_image_tag @product.image, id: :img_product%>
      <% else %>
        <%= image_tag "no_image.png" %>
      <% end %>
      <p>
        <strong>Price:</strong>$<%= @product.price%>
      </p>
      <p>
        <strong>Description</strong><%= @product.description%>
      </p>
      <p>
        <%= button_to 'Add to Cart', add_to_cart_path(@product), class: :button%>
      </p>
      <br>
      <% if @current_user.present? && @current_user.admin?%>
        <%=  link_to "Edit", edit_product_path(@product)%>
        |
        <%=  link_to "Delete", product_path(@product), method: :delete%>
      <% end %>

    </div>
    <div class="col-sm">
      <div id="map"> </div>
    </div>

      <div id="images_div">
        <%= cl_image_tag @product.image, id: :img_zoom%>
    </div>
  </div>
</div>

<script>

      function initMap() {
        var myLatLng = {lat: <%= @product.latitude %>, lng: <%= @product.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 14,
          center: myLatLng
        });
        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: "<%= @product.name %>"
        });
      }
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAJ0a73hhDIswEV4mTLGjmLIx4oHHFUelM&callback=initMap">
    </script>

app/views/session/new.html.erb
<h1>Login</h1>
<strong> <%= flash[:error] %></strong>
<%= form_tag login_path do %>

  <%= label_tag :email %>
  <%= email_field_tag :email, nil%>
  <br>
  <br>
  <%= label_tag :password %>
  <%= password_field_tag :password, nil%>
  <br>
  <br>
  <%= submit_tag 'Login'%>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |u| %>
      <li>
        <%= u.name%>
      </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create an Account</h1>

<% if flash[:errors] %>
<strong>Please correct the following errors:</strong>
<ol>
  <% flash[:errors].each do |e| %>
  <li><%= e %></li>
  <% end %>
</ol>
<% end %>

<%= form_for @user do |f| %>

  <%= f.label :name, "User Name" %>
  <%= f.text_field :name%>
  <br>
  <%= f.label :email, "Email Address" %>
  <%= f.text_field :email%>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password%>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation%>
  <br>
  <%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h1>Profile: <%= @user.name%></h1>
<p>Email: <%= @user.email%></p>
<code>
  <% @user %>
</code>